### ISSUE TITLE
Add conversion_value column

### ISSUE THREAD

**Issue by gustavodsantana23** [devraccoon/big-data-orm#59]
Wordchomper needs conversion_value attribute for each search term.

`AttributeError: 'AdwordsSearchTerm' object has no attribute 'conversion_value'`

**Comment by carlosplf** [comment]
Done. Field *total_conversion_value* is inside AdwordsSearchTerm class.

For more information, please visit https://github.com/devraccoon/big-data-orm/wiki/BigQuery-tables
